---
- name: "Upgrade mysql on other nodes"
  serial: 1
  hosts: control
  tasks:
    - name: "Remove old packages"
      apt: "name={{ item }} state=absent"
      with_items:
        - percona-xtradb-cluster-server-5.5
        - percona-xtradb-cluster-common-5.5
        - percona-xtradb-cluster-client-5.5
        - percona-xtradb-cluster-galera-3.x
      when: facter_cirrus_instance_number != 1

    - name: "Set read_only=ON"
      shell: "/bin/echo -e '[mysqld]\nread_only=ON' >
                 /etc/mysql/conf.d/upgrade.cnf"
      when: facter_cirrus_instance_number != 1

    - name: "Install new packages"
      apt: "name=percona-xtradb-cluster-56 state=present"
      when: facter_cirrus_instance_number != 1

    - name: "ensure mysql is in readonly mode"
      command: "mysql -u root -e \"show variables like 'read_only'\""
      when: facter_cirrus_instance_number != 1
      retries: 10
      delay: 10
      register: result
      until: result.stdout.find('read_only\tON') >= 0

    - name: "Check galera health"
      command: /usr/local/bin/clustercheck
      environment:
        AVAILABLE_WHEN_READONLY: 1
      when: facter_cirrus_instance_number != 1
      register: result
      until: result.rc == 0
      retries: 10
      delay: 10

    - name: "wait to check status for 1 hour (manually)"
      pause: minutes=60
      when: facter_cirrus_instance_number != 1
